// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/admin-login": {
    params: {};
  };
  "/advertiser": {
    params: {};
  };
  "/publisher": {
    params: {};
  };
  "/install": {
    params: {};
  };
  "/admin": {
    params: {};
  };
  "/user": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/admin-login" | "/advertiser" | "/publisher" | "/install" | "/admin" | "/user";
  };
  "routes/admin-login.tsx": {
    id: "routes/admin-login";
    page: "/admin-login";
  };
  "routes/advertiser.tsx": {
    id: "routes/advertiser";
    page: "/advertiser";
  };
  "routes/publisher.tsx": {
    id: "routes/publisher";
    page: "/publisher";
  };
  "routes/install.tsx": {
    id: "routes/install";
    page: "/install";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/admin.tsx": {
    id: "routes/admin";
    page: "/admin";
  };
  "routes/user.tsx": {
    id: "routes/user";
    page: "/user";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/admin-login": typeof import("./app/routes/admin-login.tsx");
  "routes/advertiser": typeof import("./app/routes/advertiser.tsx");
  "routes/publisher": typeof import("./app/routes/publisher.tsx");
  "routes/install": typeof import("./app/routes/install.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/admin": typeof import("./app/routes/admin.tsx");
  "routes/user": typeof import("./app/routes/user.tsx");
};